#define WIFI_SSID ""
#define WIFI_PASSWORD ""
#define MQTT_SERVER "Pull from creds file"
#define MQTT_USER "Pull from creds file"
#define MQTT_PASSWORD "Pull from creds file"
#define BASE_STATION_CLIENT_ID "eOS-baseGroup#"
#define PUZZLE_CLIENT_ID "eOS-puzzleGroup#"
#define BASE_STATION_TOPIC "test-base_station"
#define COMMAND_TOPIC "eOS-puzzleGroup#-command"
#define SHOW_DEBUG "true"