#define WIFI_SSID "Ethan's iPhone"
#define WIFI_PASSWORD "kendallsux"
#define MQTT_SERVER "broker.escapeos.com"
#define MQTT_USER "byupe_s25"
#define MQTT_PASSWORD "cognitive17-Rhythm-ascend-preservation"
#define BASE_STATION_CLIENT_ID "eOS-baseGroup6"
#define PUZZLE_CLIENT_ID "eOS-puzzleGroup6"
#define BASE_STATION_TOPIC "test-base_station"
#define COMMAND_TOPIC "eOS-puzzleGroup6-command"
#define SHOW_DEBUG "true"
